### ISSUE TITLE
Code Lens doesn't follow the test

### ISSUE THREAD

**Issue by matepek** [hbenl/vscode-test-explorer#78] opened 2019-06-06 11:06 UTC
If I add some new line character before a test the code lens sticks to the line but not the test's starting line.
It is so annoying I had to disable it for a long time. But otherwise it would be a great feature.

<img width="334" alt="Screenshot 2019-06-06 at 13 03 07" src="https://user-images.githubusercontent.com/16504598/59028366-c3ce7600-885b-11e9-9644-8a4468c973ae.png">

**Comment by matepek** [comment] 2019-06-10 20:13
now it is even worse:
<img width="359" alt="Screenshot 2019-06-10 at 22 09 29" src="https://user-images.githubusercontent.com/16504598/59223603-a2a7b580-8bcc-11e9-8b29-76c3d5e93f85.png">

ver2.12.0

I'm not usre that it is a regression.
Also it can be related to the new vscode version.

**Comment by NINI1988** [comment] 2019-08-01 17:10
I have the same issue.
It would be nice to have a button or command to remove all the code lens lines while editing the tests.

**Comment by hbenl** [comment] 2019-08-04 17:41
Version 2.14.1 has a fix for this.
It's not always perfect, but the problem is that I am not in complete control of the CodeLens positions:
when you edit a test file, VS Code will shift the CodeLens positions to match your edits and then (after a little debouncing delay) it will ask Test Explorer for new positions. That's why the CodeLenses used to "jump around" while editing.
Now Test Explorer will also adjust the CodeLens positions, I tried to make the same adjustments that VS Code uses so that the CodeLenses don't jump anymore.

**Closed by hbenl** 2019-08-04 17:41 UTC
