### ISSUE TITLE
code lens on the wrong typescript line 

### ISSUE THREAD

**Issue by paganaye** [hbenl/vscode-test-explorer#144] opened 2020-05-24 19:54 UTC
Mocha Test Explorer works well but the Codelens is rarely on the right line. 
The image will be clearer than the explanation I hope.
I am happy to conduct some more test if required.

![image](https://user-images.githubusercontent.com/643647/82763463-443d0c80-9e08-11ea-8fef-713ed041b81d.png)

It tried changing the end of line and the settings without success.

**Comment by hbenl** [comment] 2020-05-27 18:24
Duplicate of hbenl/vscode-mocha-test-adapter#111. As a temporary workaround try adding `"mochaExplorer.monkeyPatch": false` to your settings.

**Closed by hbenl** 2020-05-27 18:24 UTC
