### ISSUE TITLE
Scrolling while test is running

### ISSUE THREAD

**Issue by jhuels** [hbenl/vscode-test-explorer#46] opened 2019-03-07 19:07 UTC
Scrolling in the test explorer with an executable expanded keeps snapping to top. If you have all of the executables collapsed scrolling works great.

![image](https://user-images.githubusercontent.com/40254454/53982196-23847c00-40c9-11e9-9036-8e42870abd63.png)

**Comment by MFueg** [comment] 2019-03-15 12:58
I experienced that scrolling always snaps to the last clicked node.
But I'd be glad if this issue would be fixed. It is pretty irritating and you have to get used to it.

**Comment by jhuels** [comment] 2019-03-15 17:18
@MFueg, yes, thanks for the clarification.  I went back and tested more and you're correct, it's the last clicked node.

> If you have all of the executables collapsed scrolling works great.

This point in my original post is incorrect.  It is whether or not the test window pane is active.  If you keep the cursor mode active in a file the scrolling works fine.

**Comment by Raagh** [comment] 2019-03-15 19:19
also encounter this problem and indeed is pretty irritating

**Comment by hbenl** [comment] 2019-03-17 15:21
This needs to be fixed in VS Code. I'm waiting for the new tree widget to be made available to extensions, hopefully it will not have this annoying behavior. If you don't want to wait, open an issue in Microsoft/vcscode (and link to this issue so we can track this).

**Comment by jhuels** [comment] 2019-03-18 20:05
Thanks @hbenl.  I searched the vscode github issue list and couldn't find anything similar.  Let me know if any of the details are incorrect.  You can probably provide more detail than me.

**Comment by connorshea** [comment] 2019-08-09 02:53
This should be fixed with today's release of VS Code?

**Comment by MFueg** [comment] 2019-08-09 05:52
Yes! I can't reproduce it with version 1.37.0 of VS Code. Wonderful!

**Comment by hbenl** [comment] 2019-08-09 08:05
Yes, it's fixed with the new tree widget in VS Code.

**Closed by hbenl** 2019-08-09 08:05 UTC

**Comment by Raagh** [comment] 2019-08-09 08:07
Awesome!!!
