### ISSUE TITLE
After reloading a suite, the skipped (but already has run) test's state dissapears

### ISSUE THREAD

**Issue by matepek** [hbenl/vscode-test-explorer#39] opened 2019-02-19 16:23 UTC
Test Explorer version: 2.5

Output window's content still available, but the icon become <skipped>

Let me know if this issue is too cheap and you need more info. Ty

**Comment by hbenl** [comment] 2019-02-19 17:46
I'm not sure I understand this correctly: What's the state of the test before and after reloading?

**Comment by matepek** [comment] 2019-02-20 06:18
After the adapter has founded the suite and loaded it the skipped test it is 'skipped'.
Then I run it (clicking only on the skipped test's play button runs it.)
Now it has 'passed' state.
Then I recompile my executable (or call `touch ...`), my adapter automatically reloads the tests in the suite.
All the tests has the same ids so the states are preserved, but not the state of that test which has the `skipped=true` property value.

**Comment by hbenl** [comment] 2019-02-23 11:05
This is by design: when the adapter marks a test as 'skipped' when it is loaded, it should mean that the test has been disabled and when the user tries to run the test it is expected that the testing framework will skip it (either not producing any test events for it or producing a 'skipped' event), but it doesn't enforce this (so if the adapter says the test is 'passed', the Test Explorer sees this as inconsistent information about the test, in this case it will follow the latest information that it got and mark the test as 'passed'). 
The reasoning for overwriting the 'passed' state when reloading the test is as follows: the test was marked as 'passed', so apparently it wasn't disabled before (otherwise it would not have been run), now the adapter reloads the tests and marks this one as 'skipped', so apparently the user has disabled the test just now and therefore its state should be updated.

I will try to update the documentation soon to explain the details about how Test Explorer handles the different test states.

**Closed by hbenl** 2019-02-23 11:05 UTC

**Comment by matepek** [comment] 2019-02-23 13:31
Skipped tests can be run by clicking the play button on their line.
I thought it is a feature, so that the user can manually run a specific skipped test.

In my scenario I  did run all the tests with one click ("run all tests" button), then I did run a specific skipped test. After this, I recompiled (tests are reloaded). I expected to see the results of the last runs also in case of the skipped tests, but as I said skipped tests loses their state. (I still can see the test output window's content which is actually contains the relevant information for me.)

So the following is not fully true:

> The reasoning for overwriting the 'passed' state when reloading the test is as follows: the test was marked as 'passed', so apparently it wasn't disabled before (otherwise it would not have been run), now the adapter reloads the tests and marks this one as 'skipped', so apparently the user has disabled the test just now and therefore its state should be updated.

It is not a big deal, just wanted to explain my workflow.
